version: "3.9"

services:
# http://localhost:9091
  datastax-studio:
    image: datastax/dse-studio
    container_name: my-studio
    environment:
      - DS_LICENSE=accept
    ports:
      - 9091:9091
    links:
      - cassandra:my-dse
    networks:
      - my_network
    depends_on:
      - cassandra

  cassandra:
    image: cassandra:latest
    container_name: 'cassandra'
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_START_RPC: "true"
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - my_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: 'zookeeper'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - my_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: 'kafka'
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-localhost}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - my_network

volumes:
  redis_data:
  cassandra-data:

networks:
  my_network:
    driver: bridge
