version: "3.8"
# http://localhost:3000
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=Pmetabase_password1$
      - MB_DB_HOST=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=Pmetabase_password1$
      - POSTGRES_DB=metabase
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  metabase-data:
  postgres-data:
