version: '3.7'
services:
  mongo:
    container_name: MongoDb
    image: mongo:latest
    environment:
      - AUTH=yes
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=p@ssw0rd
    volumes:
      - ${MONGO_HOST_DATA}/db:/data/db
    ports:
      - "27017:27017"